MODEL:
    MODEL_NAME : "conv_net_scratch_not_working"
    MODEL_ARCH: "conv_net"
    INPUT_HEIGHT: 384
    INPUT_WIDTH: 384
    CLASSES: 120

TRAIN:
    BATCH_SIZE : 128
    EPOCHS_COUNT : 3000
    LEARNING_RATE : 0.001
    KEEP_PROB : 1.0
    TF_RECORDS : ""

VAL:
    BATCH_SIZE : 128
    TF_RECORDS : ""


TEST:
    BATCH_SIZE : 200
    TF_RECORDS : ""
    OUTPUT_CSV_PATH : "/data/outputs/dog_breeds"