MODEL:
    MODEL_NAME : "small_conv_net"
    MODEL_ARCH: "conv_net"
    INPUT_HEIGHT: 98
    INPUT_WIDTH: 98
    CLASSES: 120

TRAIN:
    BATCH_SIZE : 64
    EPOCHS_COUNT : 10001
    LEARNING_RATE : 0.0001
    KEEP_PROB : 0.2
    TF_RECORDS : ""

VAL:
    BATCH_SIZE : 200
    TF_RECORDS : ""


TEST:
    BATCH_SIZE : 500
    TF_RECORDS : ""
    OUTPUT_PATH : "/data/outputs/dog_breeds"