MODEL:
    MODEL_NAME : "small_conv_net"
    INPUT_HEIGHT: 128
    INPUT_WIDTH: 128

TRAIN:
    BATCH_SIZE : 64
    EPOCHS_COUNT : 10000
    LEARNING_RATE : 0.001
    KEEP_PROB : 0.2
    TF_RECORDS : ""

VAL:
    BATCH_SIZE : 100
    TF_RECORDS : ""


TEST:
    BATCH_SIZE : 20000
    TF_RECORDS : ""
    OUTPUT_PATH : "/data/outputs/dog_breeds"