MODEL:
    MODEL_NAME: "inception_resnet_v2"
    PRETRAIN_MODEL: "inception_resnet_v2"
    PRETAIN_MODEL_URL: "http://download.tensorflow.org/models/inception_resnet_v2_2016_08_30.tar.gz"
    PRETAIN_MODEL_PATH: "/data/pretain_model/inception_resnet_v2/inception_resnet_v2_2016_08_30.ckpt"
    EXCLUDE_NODES:
      - 'InceptionResnetV2/Logits'
      - 'InceptionResnetV2/AuxLogits'
    INPUT_HEIGHT: 299
    INPUT_WIDTH: 299
    CLASSES: 120

TRAIN:
    BATCH_SIZE : 32
    EPOCHS_COUNT : 100
    LEARNING_RATE : 0.00002
    L2_WEIGHT_DECAY : 0.001
    KEEP_PROB : 0.5
    TRAINABLE_SCOPES :
      - 'InceptionResnetV2/Logits'
      - 'InceptionResnetV2/AuxLogits'
    TRAIN_EPOCHS_BEFORE_DECAY: 20
    TRAIN_RATE_DECAY_FACTOR: 0.7
    TF_RECORDS_PATH : "/data/dog_breeds/stanford_ds/train/train.tfrecord"

EVAL:
    BATCH_SIZE : 100
    TF_RECORDS : "/data/dog_breeds/stanford_ds/val/val.tfrecord"
    OUTPUT_PATH : "/data/outputs/dog_breeds/eval/"


TEST:
    BATCH_SIZE : 200
    TF_RECORDS : "/data/dog_breeds/kaggle/dogs_test.tfrecords"
    OUTPUT_PATH : "/data/outputs/dog_breeds/test/"